spring:
  application:
    name: players-lab
  task:
    scheduling:
      thread-name-prefix: players-scheduler-
    execution:
      thread-name-prefix: players-execution-
  datasource:
    url: jdbc:h2:mem:players
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        batch_fetch_style: DYNAMIC
        order_by:
          default_null_ordering: last
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    sources: com.lab.players.PlayersLabApplication
    banner-mode: console
    allow-bean-definition-overriding: true

logging:
  config: classpath:spring-log4j2.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

