version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Commit hash ${COMMIT_HASH}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - make build
      - make docker-build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - make push-to-aws
